export enum Role {
    Admin  = "admin", 
    Lector  = "lector", 
    Editor  = "editor",
    Borrar  = "borrar", 
    LectorRestaurante  = "lectorrestaurante", 
    EditorRestaurante  = "editorrestaurante", 
    BorrarRestaurante  = "borrarrestaurante", 
    LectorReceta  = "lectorreceta", 
    EditorReceta  = "editorreceta", 
    BorrarReceta  = "borrarreceta", 
    LectorProducto  = "lectorproducto", 
    EditorProducto  = "editorproducto", 
    BorrarProducto  = "borrarproducto", 
    LectorPais  = "lectorpais", 
    EditorPais  = "editorpais", 
    BorrarPais  = "borrarpais", 
    LectorCultura  = "lectorcultura", 
    EditorCultura  = "editorcultura", 
    BorrarCultura  = "borrarcultura", 
    LectorCiudad  = "lectorciudad", 
    EditorCiudad  = "editorciudad", 
    BorrarCiudad  = "borrarciudad", 
    LectorCategoria  = "lectorcategoria", 
    EditorCategoria  = "editorcategoria", 
    BorrarCategoria  = "borrarcategoria",
    LectorRegion  = "lectorregion", 
    EditorRegion  = "editorregion", 
    BorrarRegion  = "borrarregion", 
   
  }
